services:
  expense-image:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
     - ./:/application
     - /application/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev
